python getStockDay.py 1 &
python getStockDay.py 2 &
python getStockDay.py 3 &
python getStockDay.py 4 &
python getStockDay.py 5 &
python getStockDay.py 6 &
python getStockDay.py 7 &
python getStockDay.py 8 &
python getStockDay.py 9 &
python getStockDay.py 10 &
python getStockDay.py 11 &
python getStockDay.py 12 &
python getStockDay.py 13 &
python getStockDay.py 14 &
python getStockDay.py 15 &
python getStockDay.py 16 &
python getStockDay.py 17 &
python getStockDay.py 18 &
python getStockDay.py 19 &
python getStockDay.py 20 &