python getStockTick.py 1 &
python getStockTick.py 2 &
python getStockTick.py 3 &
python getStockTick.py 4 &
python getStockTick.py 5 &
python getStockTick.py 6 &
python getStockTick.py 7 &
python getStockTick.py 8 &
python getStockTick.py 9 &
python getStockTick.py 10 &
python getStockTick.py 11 &
python getStockTick.py 12 &
python getStockTick.py 13 &
python getStockTick.py 14 &
python getStockTick.py 15 &
python getStockTick.py 16 &
python getStockTick.py 17 &
python getStockTick.py 18 &
python getStockTick.py 19 &
python getStockTick.py 20 &